name: base
channels:
  - conda-forge
dependencies:
  - r-base=4.3.2
  - r-essentials
  - r-httr
  - r-qpdf
  - r-rjson
  - r-optparse
  - r-tidyverse
  - r-knitr
  - r-yaml
  - r-rmarkdown
  - docopt
  - pandoc
